### PR TITLE
fixes issues with install not finding dependencies

### PR DESCRIPTION
**Pull request by cneubauerUSGS**

### CODE REVIEW

**Comment by ihumphrey-usgs** [comment]
This fixes an issue with running the installed ISIS3 binaries under cmake for Fedora 25.

Issue with CentOS (prog24): 

cd install
setisis `pwd`
cd bin

**./crop -h**
FROM      = Null
TO        = Null
SAMPLE    = 1
NSAMPLES  = Null
SINC      = 1
LINE      = 1
NLINES    = Null
LINC      = 1
PROPSPICE = true

**./crop**
_This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Abort_

**Comment by jessemapel** [comment]
Maybe this is an issue with the c++ std library on ubuntu? I've found a couple places talk about replacing it fixing this issue
https://support.asperasoft.com/hc/en-us/articles/115003430553-Connect-won-t-start-due-to-missing-Qt-platform-plugin-xcb-

https://github.com/Studio3T/robomongo/issues/1385

Other talk about the qt.conf file being an issue

https://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by jessemapel** [comment]
Also maybe this https://forum.qt.io/topic/48556/libqxcb-so-not-found/7

make sure that in the 3rd party library there is plugins/platforms/libqxcb.so

**Comment by Kelvinrr** [comment]
Seems to be an environment issue, so I am merging

**Comment by jessemapel** [comment]
@Kelvinrr Did anyone confirm that this was just an environment issue?

**Pull request merged**
